# ГРУППЫ
- type: loadoutGroup
  id: STTrinketsGroup
  name: loadout-group-trinkets
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STTrinkets


- type: loadoutGroup
  id: STBackpackGroup
  name: loadout-group-stalker-backpack
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STBackpack


- type: loadoutGroup
  id: STOuterClothingStalkerGroup
  name: loadout-group-stalker-outerclothing
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STOuterClothingStalker


- type: loadoutGroup
  id: STMaskStalkerGroup
  name: loadout-group-stalker-mask
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STMaskStalker


- type: loadoutGroup
  id: STBeltStalkerGroup
  name: loadout-group-stalker-belt
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STBeltStalker

- type: loadoutGroup
  id: STOuterClothingBandit
  name: loadout-group-bandit-outerclothing
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STOuterClothingStalkerBandit

- type: loadoutGroup
  id: STOuterClothingDolg
  name: loadout-group-dolg-outerclothing
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STOuterClothingStalkerDolg

- type: loadoutGroup
  id: STOuterClothingFreedom
  name: loadout-group-freedom-outerclothing
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STOuterClothingStalkerFreedom

- type: loadoutGroup
  id: STOuterClothingSci
  name: loadout-group-sci-outerclothing
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STOuterClothingStalkerSci

- type: loadoutGroup
  id: STOuterClothingSeraphims
  name: loadout-group-seraphims-outerclothing
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STOuterClothingStalkerSeraphims

- type: loadoutGroup
  id: STOuterClothingStalkerClearSky
  name: loadout-group-clearsky-outerclothing
  minLimit: 0
  maxLimit: 1
  loadouts:
  - STOuterClothingStalkerClearSky

# ЛОДАУТЫ
- type: loadout
  id: STTrinkets
  equipment:
    pocket1: STBoltBagFilled

- type: loadout
  id: STBackpack
  equipment:
    back: ClothingBackpackDuffelGreenStalker

- type: loadout
  id: STOuterClothingStalker
  equipment:
    outerClothing: ClothingOuterJacketStalker

- type: loadout
  id: STMaskStalker
  equipment:
    mask: ClothingMaskGasMarlya

- type: loadout
  id: STBeltStalker
  equipment:
    belt: ClothingBeltBandolierStalker

# Бандиты
- type: loadout
  id: STOuterClothingStalkerBandit
  equipment:
    outerClothing: ClothingOuterJacketBandit

# Долг
- type: loadout
  id: STOuterClothingStalkerDolg
  equipment:
    outerClothing: ClothingOuterJacketDolg

# Свобода
- type: loadout
  id: STOuterClothingStalkerFreedom
  equipment:
    outerClothing: ClothingOuterJacketFreedom

# Ученые
- type: loadout
  id: STOuterClothingStalkerSci
  equipment:
    outerClothing: ClothingOuterJacketSCI

# Серафимы
- type: loadout
  id: STOuterClothingStalkerSeraphims
  equipment:
    outerClothing: ClothingOuterJacketSera

# Чистое небо
- type: loadout
  id: STOuterClothingStalkerClearSky
  equipment:
    outerClothing: ClothingOuterJacketCN
