- type: job
  id: StalkerDolg
  name: job-dolg
  icon: Dolg
  description: job-dolg-desc
  playTimeTracker: JobDolg
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobDolg
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: DolgGear
  supervisors: job-dolg-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
          - Duty
        - type: Access
          tags:
            - Dolg
        - type: Bands
          band: Stalker
          bandIcon: Dolg
          bandProto: STDolgBand
          bandRankId: 2
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: job
  id: StalkerHeadDolg
  name: job-head-dolg
  icon: Dolg
  description: job-head-dolg-desc
  playTimeTracker: JobHeadDolg
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobHeadDolg
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: DolgGear
  supervisors: job-head-dolg-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: NpcFactionMember
          factions:
          - Duty
        - type: Access
          tags:
            - Dolg
            - DolgHead
            - Stalker
        - type: Bands
          band: Stalker
          bandIcon: Dolg
          bandProto: STDolgBand
          bandRankId: 2
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: DolgGear
  equipment:
    id: DolgPDA

- type: stBand
  id: STDolgBand
  name: Dolg
  factionId: Dolg
  maxMembers: 35
  managingRankId: 3
  hierarchy:
    1: StalkerNoviceDolg
    2: StalkerDolg
    3: StalkerHeadDolg

# Рядовой

- type: job
  id: StalkerNoviceDolg
  name: job-novice-dolg
  icon: Dolg
  description: job-dolg-desc
  playTimeTracker: JobNoviceDolg
  whitelisted: false
  requirements:
  - !type:DepartmentTimeRequirement
    department: Stalker
    time: 15h
  - !type:SpeciesRequirement
    species:
    - Human
    - Dwarf
  startingGear: DolgGear
  supervisors: job-dolg-supervisor
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - Duty
    - type: Access
      tags:
      - DolgNovice
      - Stalker
    - type: Bands
      band: Stalker
      bandIcon: Dolg
      bandProto: STDolgBand
      bandRankId: 2
    - type: BlockTackingHolyItems
    - type: TeethPull
      teethProto: ToothStalker
      pullingItemTag: PliersStalker
      teethCount: 3
      initialTeeth: 3
